//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emarket.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;
    using System.Web;
	
	public partial class Product
    {
		
        public int id { get; set; }
		[Required(ErrorMessage = "Please Product Name is required")]
		[Display(Name = "ProductName")]
		public string name { get; set; }
		[Required(ErrorMessage = "Please Product price is required")]
		[Display(Name = "ProductPrice")]
		[DisplayFormat(DataFormatString = "{0:C}", ApplyFormatInEditMode = false)]
		public Nullable<double> price { get; set; }
        public string image { get; set; }
		[Required(ErrorMessage = "Please Product Description is required")]
		public string description { get; set; }
        public Nullable<int> category_id { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
        public virtual Category Category { get; set; }
        public virtual Cart Cart { get; set; }
    }
}
